-- ============================================================
-- FILE: 07_joins.sql
-- PROJECT: E-Commerce Customer Data Analysis
-- AUTHOR: Ujjwal Jain
-- DESCRIPTION: Split into customers & orders tables, then JOIN queries
-- ============================================================

-- ---- TABLE SETUP ----

-- Create customers table
CREATE TABLE customers AS
SELECT DISTINCT
    customer_id,
    customer_name,
    customer_age,
    gender,
    churn
FROM ecommerce_data;

-- Create orders table
CREATE TABLE orders AS
SELECT
    customer_id,
    purchase_date,
    product_category,
    total_purchase_amount,
    payment_method,
    returns
FROM ecommerce_data;

-- ---- JOIN QUERIES ----

-- Q: Show each customer's total spending along with their gender
SELECT c.gender, c.customer_id,
       SUM(o.total_purchase_amount) AS total_spending
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.gender, c.customer_id;

-- Q: Show customer name, gender and total amount spent
SELECT c.customer_name, c.gender,
       SUM(o.total_purchase_amount) AS total_spending
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_name, c.gender;

-- Q: Find customers who never made a purchase (LEFT JOIN)
SELECT c.customer_id, c.customer_name
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
WHERE o.customer_id IS NULL;

-- Q: Show total revenue generated by churned vs non-churned customers
SELECT c.churn,
       SUM(o.total_purchase_amount) AS revenue_generated
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.churn;

-- Q: Show top 5 customers by total spending with age and gender
SELECT c.customer_name, c.customer_age, c.gender,
       SUM(o.total_purchase_amount) AS total_spending
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_name, c.customer_age, c.gender
ORDER BY total_spending DESC
LIMIT 5;

-- Q: Find which product category is most popular among churned customers
SELECT o.product_category,
       COUNT(*) AS churned_purchases
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
WHERE c.churn = 1
GROUP BY o.product_category
ORDER BY churned_purchases DESC
LIMIT 1;

-- Q: Show customers who spent more than 10000 and made more than 5 purchases
SELECT c.customer_name,
       SUM(o.total_purchase_amount) AS total_spending
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_name
HAVING SUM(o.total_purchase_amount) > 10000
   AND COUNT(o.product_category) > 5;

-- Q: Find customers who purchased using Credit Card and their total spending
SELECT c.customer_name, o.payment_method,
       SUM(o.total_purchase_amount) AS total_spending
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
WHERE o.payment_method = 'Credit Card'
GROUP BY c.customer_name, o.payment_method;

-- Q: Show customers whose average purchase is below overall average (with gender and age)
SELECT c.customer_name, c.gender, c.customer_age
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_name, c.gender, c.customer_age
HAVING AVG(o.total_purchase_amount) < (
    SELECT AVG(total_purchase_amount) FROM orders
);

-- Q: Find the top spending customer in each age group
SELECT *
FROM (
    SELECT c.customer_name,
        CASE
            WHEN customer_age BETWEEN 18 AND 25 THEN '18-25'
            WHEN customer_age BETWEEN 26 AND 35 THEN '26-35'
            WHEN customer_age BETWEEN 36 AND 45 THEN '36-45'
            ELSE '46+'
        END AS age_group,
        SUM(o.total_purchase_amount) AS total_spending,
        ROW_NUMBER() OVER (
            PARTITION BY
                CASE
                    WHEN customer_age BETWEEN 18 AND 25 THEN '18-25'
                    WHEN customer_age BETWEEN 26 AND 35 THEN '26-35'
                    WHEN customer_age BETWEEN 36 AND 45 THEN '36-45'
                    ELSE '46+'
                END
            ORDER BY SUM(o.total_purchase_amount) DESC
        ) AS row_num
    FROM customers c
    LEFT JOIN orders o ON c.customer_id = o.customer_id
    GROUP BY c.customer_name, age_group
) t
WHERE row_num = 1;
